baseURL = 'https://arianayekrangi.com/'
languageCode = 'en'
defaultContentLanguage = "en"
hasCJKLanguage = true
title = 'Ariana Yekrangi'
copyright = 'Ariana Yekrangi'
theme = 'ctheme'
pagination.pagerSize = 10

[taxonomy]
  tag = "tags"
  category = "categories"
  author = "authors"

[params]
  defaultCover = ''
  email = 'yekrangiariana[at]gmail.com'
  [[params.socialMedia]]
    name = 'Twitter'
    url = 'https://x.com/YekrangiAriana'
  [[params.blogroll]]
    name = 'UN-aligned'
    url = 'www.un-aligned.org'


[params.rss]
  name = 'RSS'
  url = 'arianayekrangi.com/index.xml'

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'

[outputs]
  home = ["HTML", "RSS"]

